# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Hodeitek.HodeiShield
PackageVersion: 0.3.0
InstallerType: wix
Scope: machine
UpgradeBehavior: install
InstallModes:
- interactive
- silent
- silentWithProgress
Commands:
- hodeishield
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Hodeitek/hodeishield-cli/releases/download/v0.3.0/hodeishield-0.3.0-x86_64-pc-windows-msvc.msi
  InstallerSha256: 11B34F2F08831D97ED645AF582CD012E657CE15996BC3777B6081696D7DCDC77
  ProductCode: '{D5BA54A2-57B1-448D-B41B-AA921F39ABEB}'
  AppsAndFeaturesEntries:
  - ProductCode: '{D5BA54A2-57B1-448D-B41B-AA921F39ABEB}'
    UpgradeCode: '{32B34E35-7A3F-422A-AC44-59204CD0D59D}'
ManifestType: installer
ManifestVersion: 1.12.0
