# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Hodeitek.HodeiShield
PackageVersion: 0.2.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: hodeishield.exe
  PortableCommandAlias: hodeishield
Commands:
- hodeishield
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Hodeitek/hodeishield-cli/releases/download/v0.2.0/hodeishield-0.2.0-x86_64-pc-windows-msvc.zip
  InstallerSha256: 7BBC4977FCCB9DBC6EA284234AE520E3B56EB96C85D6D91DD1C86DFC4668A6F3
ManifestType: installer
ManifestVersion: 1.12.0
